# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 623)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("forms\\../../../Travel booking with mysql/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"font:  14pt \"Monotype Corsiva\";\n"
"\n"
"}\n"
"Qframe\n"
"{\n"
"border:2px solid  rgb(99, 99, 99);\n"
"    \n"
"}\n"
"QPushButton,QLineEdit,QComboBox,QDoubleSpinBox,QSpinBox\n"
"{\n"
"    border:2px solid rgb(170, 0, 0);\n"
"    border-radius:15px;\n"
"}\n"
"QWidget\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"  \n"
"    background-color:rgb(24, 24, 36);\n"
"}\n"
"QTableWidget {\n"
"color: rgb(255, 255, 255);\n"
"    gridline-color: #fffff8;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"color: rgb(255, 255, 255);\n"
"    background-color: #646464;\n"
"    border: 1px solid #fffff8;\n"
"}\n"
"QTableView::item:selected \n"
"{\n"
"color:white; background:#000000; font-weight:900; \n"
"}\n"
"QTableCornerButton::section\n"
"{\n"
"background-color:#232326;\n"
"}\n"
"QHeaderView::section\n"
"{\n"
"color:white; background-color:rgb(24, 24, 36)\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QToolButton{\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"border: 0px solid;\n"
"    background-color: rgb(170, 0, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(self.main_body)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.header_frame = QtWidgets.QFrame(self.frame_7)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame = QtWidgets.QFrame(self.header_frame)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(20)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.minimize_window_btn = QtWidgets.QPushButton(self.frame)
        self.minimize_window_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.minimize_window_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_window_btn.setIcon(icon1)
        self.minimize_window_btn.setObjectName("minimize_window_btn")
        self.horizontalLayout_18.addWidget(self.minimize_window_btn)
        self.restore_btn = QtWidgets.QPushButton(self.frame)
        self.restore_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.restore_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/maximize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_btn.setIcon(icon2)
        self.restore_btn.setObjectName("restore_btn")
        self.horizontalLayout_18.addWidget(self.restore_btn)
        self.close_window_btn = QtWidgets.QPushButton(self.frame)
        self.close_window_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.close_window_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window_btn.setIcon(icon3)
        self.close_window_btn.setObjectName("close_window_btn")
        self.horizontalLayout_18.addWidget(self.close_window_btn)
        self.horizontalLayout_19.addWidget(self.frame, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.header_frame, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setObjectName("stackedWidget")
        self.random_number_page = QtWidgets.QWidget()
        self.random_number_page.setObjectName("random_number_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.random_number_page)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rand_number_lcd = QtWidgets.QLCDNumber(self.random_number_page)
        self.rand_number_lcd.setFrameShape(QtWidgets.QFrame.Box)
        self.rand_number_lcd.setMode(QtWidgets.QLCDNumber.Dec)
        self.rand_number_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.rand_number_lcd.setObjectName("rand_number_lcd")
        self.verticalLayout_3.addWidget(self.rand_number_lcd)
        self.get_rand_number_btn = QtWidgets.QPushButton(self.random_number_page)
        self.get_rand_number_btn.setObjectName("get_rand_number_btn")
        self.verticalLayout_3.addWidget(self.get_rand_number_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.random_number_page)
        self.question_page = QtWidgets.QWidget()
        self.question_page.setObjectName("question_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.question_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.question_page)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setStyleSheet("font: 32pt;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.question_lbl = QtWidgets.QLabel(self.frame_11)
        self.question_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.question_lbl.setObjectName("question_lbl")
        self.gridLayout_7.addWidget(self.question_lbl, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setStyleSheet("font: 24pt ;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.answer_2_btn = QtWidgets.QPushButton(self.frame_12)
        self.answer_2_btn.setObjectName("answer_2_btn")
        self.gridLayout_6.addWidget(self.answer_2_btn, 0, 0, 1, 1)
        self.timer_lbl = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.timer_lbl.setFont(font)
        self.timer_lbl.setStyleSheet("font: 30pt ;")
        self.timer_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_lbl.setObjectName("timer_lbl")
        self.gridLayout_6.addWidget(self.timer_lbl, 0, 1, 2, 1)
        self.answer_1_btn = QtWidgets.QPushButton(self.frame_12)
        self.answer_1_btn.setStyleSheet("")
        self.answer_1_btn.setObjectName("answer_1_btn")
        self.gridLayout_6.addWidget(self.answer_1_btn, 0, 2, 1, 1)
        self.answer_4_btn = QtWidgets.QPushButton(self.frame_12)
        self.answer_4_btn.setObjectName("answer_4_btn")
        self.gridLayout_6.addWidget(self.answer_4_btn, 1, 0, 1, 1)
        self.answer_3_btn = QtWidgets.QPushButton(self.frame_12)
        self.answer_3_btn.setObjectName("answer_3_btn")
        self.gridLayout_6.addWidget(self.answer_3_btn, 1, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_12, 0, QtCore.Qt.AlignTop)
        self.gridLayout_5.addWidget(self.frame_10, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.question_page)
        self.result_page = QtWidgets.QWidget()
        self.result_page.setObjectName("result_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.result_page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.result_page)
        self.frame_3.setStyleSheet("border:2px solid rgb(0, 0, 255);\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.boys_false_btn = QtWidgets.QPushButton(self.frame_2)
        self.boys_false_btn.setIcon(icon3)
        self.boys_false_btn.setObjectName("boys_false_btn")
        self.horizontalLayout_3.addWidget(self.boys_false_btn)
        self.boys_result_btn = QtWidgets.QPushButton(self.frame_2)
        self.boys_result_btn.setStyleSheet("border:2px solid rgb(0, 0, 255);\n"
"\n"
"border-radius:5px;\n"
"\n"
"")
        self.boys_result_btn.setObjectName("boys_result_btn")
        self.horizontalLayout_3.addWidget(self.boys_result_btn)
        self.boys_true_btn = QtWidgets.QPushButton(self.frame_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boys_true_btn.setIcon(icon4)
        self.boys_true_btn.setObjectName("boys_true_btn")
        self.horizontalLayout_3.addWidget(self.boys_true_btn)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.boys_score_lbl = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boys_score_lbl.setFont(font)
        self.boys_score_lbl.setStyleSheet("font: 24pt ;")
        self.boys_score_lbl.setObjectName("boys_score_lbl")
        self.verticalLayout_6.addWidget(self.boys_score_lbl)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_6)
        self.scrollArea.setStyleSheet("\n"
"*{\n"
"border:0px solid  rgb(99, 99, 99);\n"
"\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    border:2px solid rgb(0, 0, 255);\n"
"\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 417, 425))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.boys_layout = QtWidgets.QVBoxLayout()
        self.boys_layout.setObjectName("boys_layout")
        self.gridLayout_2.addLayout(self.boys_layout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.result_page)
        self.frame_4.setStyleSheet("border:2px solid rgb(255, 164, 205);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.girls_false_btn = QtWidgets.QPushButton(self.frame_5)
        self.girls_false_btn.setIcon(icon3)
        self.girls_false_btn.setObjectName("girls_false_btn")
        self.horizontalLayout_4.addWidget(self.girls_false_btn)
        self.girls_result_btn = QtWidgets.QPushButton(self.frame_5)
        self.girls_result_btn.setStyleSheet("border:2px solid rgb(255, 164, 205);\n"
"\n"
"border-radius:5px;\n"
"\n"
"")
        self.girls_result_btn.setObjectName("girls_result_btn")
        self.horizontalLayout_4.addWidget(self.girls_result_btn)
        self.girls_true_btn = QtWidgets.QPushButton(self.frame_5)
        self.girls_true_btn.setIcon(icon4)
        self.girls_true_btn.setObjectName("girls_true_btn")
        self.horizontalLayout_4.addWidget(self.girls_true_btn)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.girls_score_lbl = QtWidgets.QLabel(self.frame_8)
        self.girls_score_lbl.setStyleSheet("font: 24pt ;")
        self.girls_score_lbl.setObjectName("girls_score_lbl")
        self.verticalLayout_8.addWidget(self.girls_score_lbl)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_8)
        self.scrollArea_2.setStyleSheet("\n"
"*{\n"
"border:0px solid  rgb(99, 99, 99);\n"
"\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    border:2px solid rgb(0, 0, 255);\n"
"\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 416, 425))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.girls_layout = QtWidgets.QVBoxLayout()
        self.girls_layout.setObjectName("girls_layout")
        self.gridLayout_4.addLayout(self.girls_layout, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.scrollArea_2)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.stackedWidget.addWidget(self.result_page)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.main_body)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.back_btn = QtWidgets.QPushButton(self.frame_9)
        self.back_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/skip-back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon5)
        self.back_btn.setIconSize(QtCore.QSize(40, 30))
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_7.addWidget(self.back_btn, 0, QtCore.Qt.AlignLeft)
        self.next_btn = QtWidgets.QPushButton(self.frame_9)
        self.next_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/skip-forward.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon6)
        self.next_btn.setIconSize(QtCore.QSize(40, 30))
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_7.addWidget(self.next_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_9)
        self.size_grip = QtWidgets.QFrame(self.main_body)
        self.size_grip.setMinimumSize(QtCore.QSize(10, 10))
        self.size_grip.setMaximumSize(QtCore.QSize(10, 10))
        self.size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.size_grip.setObjectName("size_grip")
        self.verticalLayout.addWidget(self.size_grip, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout_7.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Question bank"))
        self.get_rand_number_btn.setText(_translate("MainWindow", "Get random number"))
        self.question_lbl.setText(_translate("MainWindow", "ما هو اسمك؟"))
        self.answer_2_btn.setText(_translate("MainWindow", "PushButton"))
        self.timer_lbl.setText(_translate("MainWindow", "30"))
        self.answer_1_btn.setText(_translate("MainWindow", "مارك"))
        self.answer_4_btn.setText(_translate("MainWindow", "PushButton"))
        self.answer_3_btn.setText(_translate("MainWindow", "PushButton"))
        self.boys_false_btn.setText(_translate("MainWindow", "False"))
        self.boys_result_btn.setText(_translate("MainWindow", "Boys"))
        self.boys_true_btn.setText(_translate("MainWindow", "True"))
        self.boys_score_lbl.setText(_translate("MainWindow", "Score:"))
        self.girls_false_btn.setText(_translate("MainWindow", "False"))
        self.girls_result_btn.setText(_translate("MainWindow", "Girls"))
        self.girls_true_btn.setText(_translate("MainWindow", "True"))
        self.girls_score_lbl.setText(_translate("MainWindow", "Score:"))
import icons_rc
